version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://ollama:8000
    depends_on:
      - ollama
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    ports:
      - "8000:8000"
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false