name: condomapp

services:
  ollama:
    image: ollama/ollama:latest
    ports:
        - 11434:11434
    volumes:
        - ./data/ollama:/root/.ollama
        - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama-container
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
  streamlit:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8501:8501